# Google app engine deployment
runtime: nodejs18
env: standard
entrypoint: node index.js
automatic_scaling:
  max_instances: 2
env_variables:
  DATABASE_SERVICE: "firebase"
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
