steps:
  # Creates the production .env file
  - name: 'alpine'
    entrypoint: sh
    args: ['-c', 'printenv > packages/backend/.env']
    env:
      - DATABASE_SERVICE=firebase
      - API_KEY=$_API_KEY
      - RPC_URL=$_RPC_URL

  - name: 'alpine'
    entrypoint: 'cat'
    args: ['packages/backend/.env']

#  - name: "gcr.io/cloud-builders/gcloud"
#    entrypoint: 'bash'
#    args:
#      - '-c'
#      - |
#        cd packages/backend
#        gcloud app deploy --quiet
timeout: "1600s"
